### ISSUE TITLE
Modify get_or_create to remove ret_col and additionally return True / False

### ISSUE THREAD

**Issue by christabone** [FlyBase/harvdev-utils#10]
HI @ianlongden, @gildossantos,

Looking to update the `get_or_create` function to improve functionality (I hope) if it's OK by you both. 

First, as the function now returns an SQL Alchemy object due to Ian's changes -- the `ret_col` feature is no longer necessary. For example, you can write something like:

```
chemical = get_or_create(self.session, Feature, organism_id=organism_id,
                                     name=self.process_data['CH1a']['data'][FIELD_VALUE],
                                     type_id=chemical_id,
                                     uniquename='FBch:temp_0')`

print(chemical.name)
```

This uses `chemical.name` in the returned object to access the `name` column of the new feature you've created. This makes the `ret_col` parameter somewhat redundant as you get every column back automatically, by default.

Secondly, I'd like to have the function indicate whether a new object was created or an existing object was returned. I was thinking there would be a second returned boolean value of `True` or `False` depending on whether an object was retrieved or created. 

`True` would mean an object already existed and was returned and `False` would mean an object did _not_ exist and needed to be created. In this sense, the you could use the `True` / `False` return to decide whether or not to do other stuff in your code. In chemical curation, I would use it to raise a critical error indicating that an object already existed (when `True`) or just create the object normally and proceed (when `False`). This saves us from writing the extra "just checking" query:

```
chemical, already_existed = get_or_create(self.session, Feature, organism_id=organism_id,
                                     name=self.process_data['CH1a']['data'][FIELD_VALUE],
                                     type_id=chemical_id,
                                     uniquename='FBch:temp_0')`

if already_existed:
    raise
```

Thoughts?

**If `ret_col` is removed, we would need to be sure to modify any functions using it.** If `True` / `False` is added, it will _always_ be returned -- but Python will just ignore it if you're only assigning a single parameter to the output (i.e., you don't need to change anything in your code by default, the first code example above would still work without issue).

**Comment by gildossantos** [comment]
I would fix one script. That's manageable. Are we expecting much more churn in these utils?

**Comment by christabone** [comment]
No, not much churn at all. I went back and forth in my head before even suggesting this modification.

It would make it such a pain to keep modifying stuff -- but I feel like this one change might save us a bunch of coding.

**Comment by gildossantos** [comment]
I forgot to mention that those changes sound good to me. I did _try_ to sound non-grumpy about it.
